[package]
name = "avr-progmem-rs"
version = "0.1.0"
authors = ["Cryptjar <cryptjar@junk.studio>"]
edition = "2018"

[features]
default = []
# Enables some tweak to ease debugging, should not be use in production
dev = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
